docs_dir: src
site_name: SiteChef Theme Documentation
pages:
- [index.md, General Use, Introduction & QuickStart]
- [installation.md, General Use, Installation]
- [structure.md, General Use, Theme Structure]
- [templating.md, General Use, HTML Templating]
- [scss.md, General Use,  Stylesheets]
- [assetpipeline.md, General Use, Compiling Frontend Assets]
- [datastructure.md,General Use,  Data Structure]
- [frontendapi.md,General Use,  Frontend API Overview]
- [publishing.md, General Use, How to Publish Your Theme]
- [configfiles/sitechefrc.md, Config Files, .sitechefrc]
- [configfiles/themejson.md, Config Files, theme.json]
- [libraries/index.md, Frontend Library Reference, Overview]
- [libraries/analytics.md, Frontend Library Reference, Analytics]
- [libraries/carouselgallery.md, Frontend Library Reference, Carousel Gallery]
- [libraries/clevercrop.md, Frontend Library Reference, JQuery CleverCrop]
- [libraries/heightfix.md, Frontend Library Reference, Height Fix]
- [libraries/historyscroll.md, Frontend Library Reference, History Scroll]
- [libraries/html5video.md, Frontend Library Reference, HTML5 Video]
- [libraries/imagerotator.md, Frontend Library Reference, Image Rotator]
- [libraries/imageloader.md, Frontend Library Reference, Image Loader]
- [libraries/newsletter.md, Frontend Library Reference, Newsletter]
- [libraries/resizer.md, Frontend Library Reference, Resizer]
- [libraries/simpleparallax.md, Frontend Library Reference, Simple Parallax]
- [libraries/screenheight.md, Frontend Library Reference, Screen Height]
- [libraries/styleddropdown.md, Frontend Library Reference, Styled Dropdown]
- [libraries/striploader.md, Frontend Library Reference, Strip Loader]
- [libraries/swipes.md, Frontend Library Reference, Swipes]
- [libraries/twitter.md, Frontend Library Reference, Twitter]
- [libraries/videoclick.md, Frontend Library Reference, Video Click]
theme_dir: theme
google_analytics:
  - UA-51231189-4
  - sitechef.co.uk
copyright: SiteChef 2014
site_dir: docs
